#!/bin/bash

PATCHING_YEAR=`date +%Y`

echo "January-`date +%Y`"
echo "=================================="
echo "Non-PROD :: `cal 01 ${PATCHING_YEAR} | awk 'NR>2 {print $3}' | grep -v "^$" | sed -n '2p'`-01-${PATCHING_YEAR}"
echo "PROD     :: `cal 01 ${PATCHING_YEAR} | awk 'NR>2 {print $5}' | grep -v "^$" | sed -n '2p'`-01-${PATCHING_YEAR}"
printf "\n"

echo "February-`date +%Y`"
echo "=================================="
echo "Non-PROD :: `cal 02 ${PATCHING_YEAR} | awk 'NR>2 {print $3}' | grep -v "^$" | sed -n '2p'`-02-${PATCHING_YEAR}"
echo "PROD     :: `cal 02 ${PATCHING_YEAR} | awk 'NR>2 {print $5}' | grep -v "^$" | sed -n '2p'`-02-${PATCHING_YEAR}"
printf "\n"

echo "March-`date +%Y`"
echo "=================================="
echo "Non-PROD :: `cal 03 ${PATCHING_YEAR} | awk 'NR>2 {print $3}' | grep -v "^$" | sed -n '2p'`-03-${PATCHING_YEAR}"
echo "PROD     :: `cal 03 ${PATCHING_YEAR} | awk 'NR>2 {print $5}' | grep -v "^$" | sed -n '2p'`-03-${PATCHING_YEAR}"
printf "\n"

echo "April-`date +%Y`"
echo "=================================="
echo "Non-PROD :: `cal 04 ${PATCHING_YEAR} | awk 'NR>2 {print $3}' | grep -v "^$" | sed -n '2p'`-04-${PATCHING_YEAR}"
echo "PROD     :: `cal 04 ${PATCHING_YEAR} | awk 'NR>2 {print $5}' | grep -v "^$" | sed -n '2p'`-04-${PATCHING_YEAR}"
printf "\n"

echo "May-`date +%Y`"
echo "=================================="
echo "Non-PROD :: `cal 05 ${PATCHING_YEAR} | awk 'NR>2 {print $3}' | grep -v "^$" | sed -n '2p'`-05-${PATCHING_YEAR}"
echo "PROD     :: `cal 05 ${PATCHING_YEAR} | awk 'NR>2 {print $5}' | grep -v "^$" | sed -n '2p'`-05-${PATCHING_YEAR}"
printf "\n"

echo "June-`date +%Y`"
echo "=================================="
echo "Non-PROD :: `cal 06 ${PATCHING_YEAR} | awk 'NR>2 {print $3}' | grep -v "^$" | sed -n '2p'`-06-${PATCHING_YEAR}"
echo "PROD     :: `cal 06 ${PATCHING_YEAR} | awk 'NR>2 {print $5}' | grep -v "^$" | sed -n '2p'`-06-${PATCHING_YEAR}"
printf "\n"

echo "July-`date +%Y`"
echo "=================================="
echo "Non-PROD :: `cal 07 ${PATCHING_YEAR} | awk 'NR>2 {print $3}' | grep -v "^$" | sed -n '2p'`-07-${PATCHING_YEAR}"
echo "PROD     :: `cal 07 ${PATCHING_YEAR} | awk 'NR>2 {print $5}' | grep -v "^$" | sed -n '2p'`-07-${PATCHING_YEAR}"
printf "\n"

echo "August-`date +%Y`"
echo "=================================="
echo "Non-PROD :: `cal 08 ${PATCHING_YEAR} | awk 'NR>2 {print $3}' | grep -v "^$" | sed -n '2p'`-08-${PATCHING_YEAR}"
echo "PROD     :: `cal 08 ${PATCHING_YEAR} | awk 'NR>2 {print $5}' | grep -v "^$" | sed -n '2p'`-08-${PATCHING_YEAR}"
printf "\n"

echo "September-`date +%Y`"
echo "=================================="
echo "Non-PROD :: `cal 09 ${PATCHING_YEAR} | awk 'NR>2 {print $3}' | grep -v "^$" | sed -n '2p'`-09-${PATCHING_YEAR}"
echo "PROD     :: `cal 09 ${PATCHING_YEAR} | awk 'NR>2 {print $5}' | grep -v "^$" | sed -n '2p'`-09-${PATCHING_YEAR}"
printf "\n"

echo "October-`date +%Y`"
echo "=================================="
echo "Non-PROD :: `cal 10 ${PATCHING_YEAR} | awk 'NR>2 {print $3}' | grep -v "^$" | sed -n '2p'`-10-${PATCHING_YEAR}"
echo "PROD     :: `cal 10 ${PATCHING_YEAR} | awk 'NR>2 {print $5}' | grep -v "^$" | sed -n '2p'`-10-${PATCHING_YEAR}"
printf "\n"

echo "November-`date +%Y`"
echo "=================================="
echo "Non-PROD :: `cal 11 ${PATCHING_YEAR} | awk 'NR>2 {print $3}' | grep -v "^$" | sed -n '2p'`-11-${PATCHING_YEAR}"
echo "PROD     :: `cal 11 ${PATCHING_YEAR} | awk 'NR>2 {print $5}' | grep -v "^$" | sed -n '2p'`-11-${PATCHING_YEAR}"
printf "\n"

echo "December-`date +%Y`"
echo "=================================="
echo "Non-PROD :: `cal 12 ${PATCHING_YEAR} | awk 'NR>2 {print $3}' | grep -v "^$" | sed -n '2p'`-12-${PATCHING_YEAR}"
echo "PROD     :: `cal 12 ${PATCHING_YEAR} | awk 'NR>2 {print $5}' | grep -v "^$" | sed -n '2p'`-12-${PATCHING_YEAR}"
printf "\n"
